# Generated by Django 4.0.4 on 2023-01-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('high_score', models.IntegerField(max_length=10)),
            ],
        ),
    ]
