# Generated by Django 4.0.4 on 2023-01-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helicopter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='high_score',
            field=models.IntegerField(),
        ),
    ]
